"""empty message

Revision ID: 06c353fe2c95
Revises: 4a1772a9cf47
Create Date: 2024-07-06 10:30:31.010930

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '06c353fe2c95'
down_revision: Union[str, None] = '4a1772a9cf47'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('account', sa.Column('client_id', sa.Integer(), nullable=False))
    op.add_column('account', sa.Column('client_secret', sa.String(), nullable=False))
    op.add_column('account', sa.Column('code', sa.String(), nullable=False))
    op.drop_constraint('account_access_token_key', 'account', type_='unique')
    op.drop_column('account', 'access_token')
    op.add_column('contact', sa.Column('vk_id', sa.Integer(), nullable=False))
    op.drop_constraint('contact_email_key', 'contact', type_='unique')
    op.create_unique_constraint(None, 'contact', ['vk_id'])
    op.drop_column('contact', 'email')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contact', sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'contact', type_='unique')
    op.create_unique_constraint('contact_email_key', 'contact', ['email'])
    op.drop_column('contact', 'vk_id')
    op.add_column('account', sa.Column('access_token', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.create_unique_constraint('account_access_token_key', 'account', ['access_token'])
    op.drop_column('account', 'code')
    op.drop_column('account', 'client_secret')
    op.drop_column('account', 'client_id')
    # ### end Alembic commands ###
