"""empty message

Revision ID: 4a1772a9cf47
Revises: 5dba0b69b71f
Create Date: 2024-07-05 09:23:47.418880

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4a1772a9cf47'
down_revision: Union[str, None] = '5dba0b69b71f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('account', sa.Column('access_token', sa.String(), nullable=False))
    op.drop_constraint('account_login_key', 'account', type_='unique')
    op.create_unique_constraint(None, 'account', ['access_token'])
    op.drop_column('account', 'login')
    op.drop_column('account', 'hashed_password')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('account', sa.Column('hashed_password', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('account', sa.Column('login', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'account', type_='unique')
    op.create_unique_constraint('account_login_key', 'account', ['login'])
    op.drop_column('account', 'access_token')
    # ### end Alembic commands ###
