"""empty message

Revision ID: 5dba0b69b71f
Revises: cfcfa2a331a3
Create Date: 2024-07-05 08:15:32.511537

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5dba0b69b71f'
down_revision: Union[str, None] = 'cfcfa2a331a3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contact', sa.Column('email', sa.String(), nullable=False))
    op.drop_constraint('contact_vk_id_key', 'contact', type_='unique')
    op.create_unique_constraint(None, 'contact', ['email'])
    op.drop_column('contact', 'last_name')
    op.drop_column('contact', 'vk_id')
    op.drop_column('contact', 'first_name')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contact', sa.Column('first_name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('contact', sa.Column('vk_id', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('contact', sa.Column('last_name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'contact', type_='unique')
    op.create_unique_constraint('contact_vk_id_key', 'contact', ['vk_id'])
    op.drop_column('contact', 'email')
    # ### end Alembic commands ###
